### ISSUE TITLE
Dependency not found - @quasar/quasar-app-extension-colorize

### ISSUE THREAD

**Issue by apasov** [quasarframework/app-extension-qiconpicker#15]
When compiling with v1.0.3 I get this error:
`Extension(@quasar/qiconpicker): Dependency not found - @quasar/quasar-app-extension-colorize. Please install it.`

![image](https://user-images.githubusercontent.com/28765662/65598893-c389f000-df9c-11e9-9977-72796969d853.png)

**Comment by hawkeye64** [comment]
`quasar ext add @quasar/colorize`
We are working on a new way to handle issues where AEs are dependent on other AEs.
