### ISSUE TITLE
[Question] Is QIconPicker ready for production?

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [quasarframework/app-extension-qiconpicker#3]
I have some places in my project admin panel to use it.
And interesting is it ready for production?
I can test on my project.

**Comment by hawkeye64** [comment]
Well, there is a few more things I would like to do with it. But, those things should not break current functionality.
And, the more people that use it the more tested it will be. Go ahaead and test with it and give some suggestions if you like.
