### ISSUE TITLE
Some Fontawesome and Ion icons not displayed

### ISSUE THREAD

**Issue by apasov** [quasarframework/app-extension-qiconpicker#5]
Thank you for this great extension!
There are problems with some of the icons.
Fontawesome:
![image](https://user-images.githubusercontent.com/28765662/61534004-b4337700-aa2e-11e9-8a53-8f09a3162d07.png)

Ion:
![image](https://user-images.githubusercontent.com/28765662/61533907-6dde1800-aa2e-11e9-8e3a-00b60e0fa86f.png)

**Comment by hawkeye64** [comment]
Thanks for the info. I'll investigate and see what might be causing the issue .

**Comment by hawkeye64** [comment]
Here's what I have: 
![image](https://user-images.githubusercontent.com/10262924/63389550-51086d80-c369-11e9-994c-0c23f6a92102.png)
As you can see, the fonts are showing up for me.
From your screenshots, are they from the demo site, or did you fork the branch?

**Comment by apasov** [comment]
The screenshots are from the demo site. Also I use this extension in a project of my own with the same result - some icons are absent. I test in latest Firefox and Chrome on Windows
![image](https://user-images.githubusercontent.com/28765662/63435657-99866080-c427-11e9-99aa-f0cc38525f79.png)

Hope it helps.

**Comment by hawkeye64** [comment]
Fixed in v1.0.2
I have hand-currated all the fonts with issues. Let me know if you find any more.
