### ISSUE TITLE
Wish you could select the number of icons to display per page.

### ISSUE THREAD

**Issue by tohagan** [quasarframework/app-extension-qiconpicker#7]
Would be nice to be able to quickly select the number of icons or rows of icons to display on a page. Rather than a drop down list (two clicks) would be smoother to just use hyperlinks with "|" delimiters (one tap/click) as in ...

[10](10) | [20](20) | [50](50) | [100](100) | [200](200)

Thanks for more Quasar Awesomeness - just gets better!

**Comment by hawkeye64** [comment]
Hey, thanks for taking time to make this observation.

I take it you are noting the examples? This is in devland and if you use the App Extension can control it however you like through the `pagination` property.

**Comment by tohagan** [comment]
Sure ... you're right .. I was using your demo to find icons.
